import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { COMPANIONS } from '../content/companions';
import type { QuickReply } from '../content/companions';
import { useStatsStore } from './statsStore';
import { getGeminiResponse, isGeminiAvailable } from '../utils/geminiService';

export interface ChatMessage {
  id: string;
  sender: 'user' | 'companion';
  text: string;
  translation: string;
  timestamp: string;
  quickReplies?: QuickReply[];
  signOff?: string;
  /** Whether this message was generated by Gemini AI. */
  isAiGenerated?: boolean;
}

export interface CompanionConversation {
  messages: ChatMessage[];
  letterCount: number;
  friendshipExp: number;
  friendshipLevel: number;
}

interface CompanionState {
  activeCompanionId: string;
  conversations: Record<string, CompanionConversation>;
  isTyping: boolean;
  
  setActiveCompanion: (id: string) => void;
  sendUserMessage: (companionId: string, text: string, nextNodeId?: string) => void;
  resetConversations: () => void;
}

const getInitialMessageForCompanion = (companionId: string): ChatMessage => {
  const companion = COMPANIONS[companionId];
  const startNode = companion.dialogueNodes[companion.greetingNodeId];
  return {
    id: `${companionId}-init`,
    sender: 'companion',
    text: startNode.text,
    translation: startNode.translation,
    timestamp: new Date().toLocaleDateString([], { month: 'short', day: 'numeric' }),
    quickReplies: startNode.quickReplies,
    signOff: startNode.signOff,
  };
};

const createFreshConversations = (): Record<string, CompanionConversation> => {
  return {
    elena: {
      messages: [getInitialMessageForCompanion('elena')],
      letterCount: 1,
      friendshipExp: 0,
      friendshipLevel: 1,
    },
    mateo: {
      messages: [getInitialMessageForCompanion('mateo')],
      letterCount: 1,
      friendshipExp: 0,
      friendshipLevel: 1,
    },
    diego: {
      messages: [getInitialMessageForCompanion('diego')],
      letterCount: 1,
      friendshipExp: 0,
      friendshipLevel: 1,
    },
  };
};

/**
 * Build a companion reply from the static dialogue tree (original behavior).
 * Used as a fallback when Gemini is unavailable or when a quick-reply chip is selected.
 */
function getDialogueTreeReply(
  companionId: string,
  conv: CompanionConversation,
  nextNodeId?: string,
): ChatMessage {
  const companion = COMPANIONS[companionId];
  let nextNode = companion.dialogueNodes[companion.greetingNodeId];

  if (nextNodeId && companion.dialogueNodes[nextNodeId]) {
    // User selected a quick reply chip
    nextNode = companion.dialogueNodes[nextNodeId];
  } else {
    // User typed custom free-text; transition using current node's fallbackReply
    const lastCompanionMsg = [...conv.messages]
      .reverse()
      .find((m) => m.sender === 'companion');

    if (lastCompanionMsg) {
      const currentNodeId = Object.keys(companion.dialogueNodes).find(
        (key) => companion.dialogueNodes[key].text === lastCompanionMsg.text
      );

      if (currentNodeId) {
        const currentNode = companion.dialogueNodes[currentNodeId];
        if (currentNode.fallbackReply) {
          nextNode = companion.dialogueNodes[currentNode.fallbackReply.nextNodeId] || nextNode;
          if (currentNode.fallbackReply.text) {
            nextNode = {
              ...nextNode,
              text: currentNode.fallbackReply.text,
              translation: currentNode.fallbackReply.translation,
            };
          }
        }
      }
    }
  }

  return {
    id: `${companionId}-${Date.now()}`,
    sender: 'companion',
    text: nextNode.text,
    translation: nextNode.translation,
    timestamp: new Date().toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
    }),
    quickReplies: nextNode.quickReplies,
    signOff: nextNode.signOff,
  };
}

/**
 * Call Gemini to generate an AI-powered response for free-text messages.
 * Returns null if the API is unavailable or the call fails.
 */
async function getAiReply(
  companionId: string,
  userText: string,
  conv: CompanionConversation,
): Promise<ChatMessage | null> {
  const companion = COMPANIONS[companionId];

  // Build recent conversation history for context
  const recentMessages = conv.messages.slice(-12).map((msg) => ({
    role: msg.sender === 'user' ? ('user' as const) : ('companion' as const),
    text: msg.text,
  }));

  const geminiResponse = await getGeminiResponse(
    companionId,
    userText,
    {
      name: companion.name,
      role: companion.role,
      bio: companion.bio,
      speed: companion.speed,
    },
    recentMessages,
  );

  if (!geminiResponse) return null;

  // Convert Gemini quick replies to the QuickReply format
  // AI-generated quick replies don't have a nextNodeId, so we use a special
  // marker that tells the store to route them through Gemini again
  const quickReplies: QuickReply[] = geminiResponse.quickReplies.map((qr) => ({
    text: qr.text,
    translation: qr.translation,
    nextNodeId: '__gemini__', // Sentinel: tells sendUserMessage to use Gemini path
  }));

  return {
    id: `${companionId}-${Date.now()}`,
    sender: 'companion',
    text: geminiResponse.text,
    translation: geminiResponse.translation,
    timestamp: new Date().toLocaleTimeString([], {
      hour: '2-digit',
      minute: '2-digit',
    }),
    quickReplies,
    signOff: geminiResponse.signOff,
    isAiGenerated: true,
  };
}

export const useCompanionStore = create<CompanionState>()(
  persist(
    (set, get) => ({
      activeCompanionId: 'elena',
      conversations: createFreshConversations(),
      isTyping: false,

      setActiveCompanion: (id) => set({ activeCompanionId: id }),

      sendUserMessage: (companionId, text, nextNodeId) => {
        const timestamp = new Date().toLocaleTimeString([], {
          hour: '2-digit',
          minute: '2-digit',
        });
        const userMsg: ChatMessage = {
          id: `user-${Date.now()}`,
          sender: 'user',
          text,
          translation: '',
          timestamp,
        };

        // 1. Award base stats (+10 XP, +5 Coins)
        useStatsStore.getState().addRewards(10, 5);

        // 2. Update conversation progress & user message
        let levelUpAwarded = false;
        
        set((state) => {
          const conv = state.conversations[companionId];
          const newMessages = [...conv.messages, userMsg];
          const newLetterCount = conv.letterCount + 1;
          
          let newExp = conv.friendshipExp + 15; // +15 friendship exp per letter exchange
          let newLevel = conv.friendshipLevel;
          const expThreshold = newLevel * 100;
          
          if (newExp >= expThreshold) {
            newExp = newExp - expThreshold;
            newLevel = newLevel + 1;
            levelUpAwarded = true;
          }

          return {
            isTyping: true,
            conversations: {
              ...state.conversations,
              [companionId]: {
                messages: newMessages,
                letterCount: newLetterCount,
                friendshipExp: newExp,
                friendshipLevel: newLevel,
              },
            },
          };
        });

        // 3. Grant level up bonus if applicable
        if (levelUpAwarded) {
          useStatsStore.getState().addRewards(0, 50); // +50 Coin bonus for friendship level-up
        }

        // 4. Determine whether to use Gemini AI or the static dialogue tree
        const useGemini =
          isGeminiAvailable() &&
          // Use Gemini for free-text (no nextNodeId) or AI-generated quick replies
          (!nextNodeId || nextNodeId === '__gemini__');

        if (useGemini) {
          // ─── AI-powered path: call Gemini ───
          const conv = get().conversations[companionId];
          getAiReply(companionId, text, conv)
            .then((aiMsg) => {
              if (aiMsg) {
                // Success: use the AI response
                set((state) => ({
                  isTyping: false,
                  conversations: {
                    ...state.conversations,
                    [companionId]: {
                      ...state.conversations[companionId],
                      messages: [...state.conversations[companionId].messages, aiMsg],
                      letterCount: state.conversations[companionId].letterCount + 1,
                    },
                  },
                }));
              } else {
                // Gemini failed, fall back to dialogue tree
                const fallbackConv = get().conversations[companionId];
                const fallbackMsg = getDialogueTreeReply(companionId, fallbackConv);
                set((state) => ({
                  isTyping: false,
                  conversations: {
                    ...state.conversations,
                    [companionId]: {
                      ...state.conversations[companionId],
                      messages: [...state.conversations[companionId].messages, fallbackMsg],
                      letterCount: state.conversations[companionId].letterCount + 1,
                    },
                  },
                }));
              }
            })
            .catch(() => {
              // Error: fall back to dialogue tree
              const fallbackConv = get().conversations[companionId];
              const fallbackMsg = getDialogueTreeReply(companionId, fallbackConv);
              set((state) => ({
                isTyping: false,
                conversations: {
                  ...state.conversations,
                  [companionId]: {
                    ...state.conversations[companionId],
                    messages: [...state.conversations[companionId].messages, fallbackMsg],
                    letterCount: state.conversations[companionId].letterCount + 1,
                  },
                },
              }));
            });
        } else {
          // ─── Static dialogue tree path (original behavior) ───
          setTimeout(() => {
            const conv = get().conversations[companionId];
            const companionMsg = getDialogueTreeReply(companionId, conv, nextNodeId);

            set((state) => ({
              isTyping: false,
              conversations: {
                ...state.conversations,
                [companionId]: {
                  ...state.conversations[companionId],
                  messages: [...state.conversations[companionId].messages, companionMsg],
                  letterCount: state.conversations[companionId].letterCount + 1,
                },
              },
            }));
          }, 1500);
        }
      },

      resetConversations: () =>
        set({
          conversations: createFreshConversations(),
          isTyping: false,
        }),
    }),
    {
      name: 'wayfarer-companions',
      partialize: (state) => ({
        activeCompanionId: state.activeCompanionId,
        conversations: state.conversations,
      }),
    }
  )
);
